# Generated by Django 3.2.2 on 2021-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.IntegerField(max_length=5)),
                ('term', models.DecimalField(decimal_places=0, max_digits=1)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
